spring:
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}?currentSchema=${PG_SCHEMA}
    driver-class-name: org.postgresql.Driver
    password: ${PG_PASSWD}
    username: ${PG_USER}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    database: postgresql
